### ISSUE TITLE
Genel soru sorma

### ISSUE THREAD

**Issue by shibby** [Resmin/Resmin#182]
Sorular sanırsam sadece kullanıcılara sorulabiliyor. 
Bunu geliştirip, ister kullanıcıya özel, ister genel soru sorulmalı. Ortaya attım birisi, yanıtlasın gibisinden. (ekşideki ukte mantığı)

**Comment by miratcan** [comment]
:+1:

**Comment by miratcan** [comment]
Bunun işi ayrı.
