### ISSUE TITLE
Cevapların daha çok kişiye ulaşmasını sağlamak

### ISSUE THREAD

**Issue by coderontheroad** [Resmin/Resmin#197]
Şimdi, anladığım kadarıyla duvarımda takip ettiklerimin cevapları gözüküyor. Bunu biraz değiştirsek takip ettiklerimin kalplediği ve yorumladığı cevaplarda duvara düşse (ffdeki gibi) hem takipçisi olmayanlarda daha çok kişiye ulaşmış olur hemde sitedeki etkileşim daha çok artar diye düşünmekteyim.

Sevgiler...

**Comment by shibby** [comment]
+1

ama bunun için tasarım değişikliğine gidilmesi gerekebilir. o görselin bizim duvarımıza neden düştüğünü iyi anlamamız lazım. (takip ettiğim kişi, takip ettiğimiz yorumladığı görsel, kalplediği görsel.. gibi)

**Comment by miratcan** [comment]
Bunu yapmak için tek sütunlu tasarıma geçmek lazım ya. Her gönderinin başında: *shibby şuna yorum yaptı* gibi bir metin olması gerekli. yapılabilir aslında.

**Comment by ogomogo** [comment]
Bildirimler sayfasini duzenleyip (tasarim + yayinlanan bilginin zenginlestirilmesi), baglantili oldugumuz kisilere dair aksiyonlari da gostermek ise yarayabilir.

**Comment by miratcan** [comment]
Buna artık gerek yok.
