### ISSUE TITLE
Bildirim silinmesi

### ISSUE THREAD

**Issue by shibby** [Resmin/Resmin#198]
Bir görsel ile ilgili onlarca bildirim gelebiliyor. X yorum yaptı, Z beğendi, Y onun arkasından konuştu...

http://resm.in/s/UNIQ/?nid=BILDIRIMID

Bir bildirime tıkladığımızda bildirimleri silerken urldeki bildirim id sine göre değil görsel uniqine göre silinmeli bence.

**Comment by miratcan** [comment]
mantıklı
