### ISSUE TITLE
Link'in sonunda P etiketi sorunu

### ISSUE THREAD

**Issue by coderontheroad** [Resmin/Resmin#202]
http://resm.in/s/DEE/

Şurdaki cevapta açıklama kısmındaki linkin sonuna '</p>' koydu sistem link bozuk gidiyor bu yüzden :)
Ayrıca linkleri kısaltarak göstersek ve linke tıklayınca yeni sekmede açsa çok daha güzel olur diye düşünüyorum.

**Comment by miratcan** [comment]
Markdown işi ile birlikte çözülecek.

**Comment by ogomogo** [comment]
Markdown a bence gerek yok. kiremiti once kirip, sonra yapistiriciyla
yapistirmak gibi oluyor. sorun baska bir sey. :)

su sayfada
https://docs.djangoproject.com/es/1.9/ref/templates/builtins/#urlize

sunu diyor:
If urlize is applied to text that already contains HTML markup, things
won’t work as expected. Apply this filter only to plain text.

Test edemedigim icin bakamiyorum ama su sayfada
https://github.com/Resmin/Resmin/blob/master/resmin/templates/story/story_detail_inc.html
81. satirdaki filtrelerin sirasini degistirsen sorun cozulur diye
dusunuyorum. yani:

x > {{ story.description|linebreaks|urlize }}
yerine
o > {{ story.description|urlize|linebreaks }} yapilirsa hallolur bence. Once
URL leri taglestirip, ondan sonra <p> etiketlerini oturtur..

tabii test edemedigim icin bir sey diyemeyecegim. Bir de Markdown hic
gelmesin ya.




2016-02-13 12:58 GMT+01:00 Mirat Can Bayrak <notifications@github.com>:

**Comment by shibby** [comment]
Markdown gelmesin +1

16 Şubat 2016 07:28 tarihinde Ogo <notifications@github.com> yazdı:

> Markdown a bence gerek yok. kiremiti once kirip, sonra yapistiriciyla
> yapistirmak gibi oluyor. sorun baska bir sey. :)
>
> su sayfada
> https://docs.djangoproject.com/es/1.9/ref/templates/builtins/#urlize
>
> sunu diyor:
> If urlize is applied to text that already contains HTML markup, things
> won’t work as expected. Apply this filter only to plain text.
>
> Test edemedigim icin bakamiyorum ama su sayfada
>
> https://github.com/Resmin/Resmin/blob/master/resmin/templates/story/story_detail_inc.html
> 81. satirdaki filtrelerin sirasini degistirsen sorun cozulur diye
> dusunuyorum. yani:
>
> x > {{ story.description|linebreaks|urlize }}
> yerine
> o > {{ story.description|urlize|linebreaks }} yapilirsa hallolur bence.
> Once
> URL leri taglestirip, ondan sonra <p> etiketlerini oturtur..
>
> tabii test edemedigim icin bir sey diyemeyecegim. Bir de Markdown hic
> gelmesin ya.
>
>
>
>
> 2016-02-13 12:58 GMT+01:00 Mirat Can Bayrak <notifications@github.com>:
>
> > Markdown işi ile birlikte çözülecek.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Resmin/Resmin/issues/202#issuecomment-183654559>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Resmin/Resmin/issues/202#issuecomment-184527198>.
>



-- 
Güven Atbakan
0532 433 87 16
http://www.guvenatbakan.com

**Comment by miratcan** [comment]
markdown gelecek.
