### ISSUE TITLE
silinmis hesap takip edenler kisminda gorunuyor

### ISSUE THREAD

**Issue by ogomogo** [Resmin/Resmin#204]
/u/USER/followings/ de ve /u/USER/followers/ gorunen listelerde uzerine tiklandiginda:

> Not Found
> The requested URL /u/USER2/ was not found on this server.

hatasi veren kullanicilar var.

Kullanici adi "nianto". Eger kullanici suspend olduysa bu sayfalarda listelenmemesini saglamak gerekir. 

Eger hesap silinme islemiyle ilgili bir durumsa bu dosyayi kapatip "hesap silinmenin iyilestirilmesi" uzerine yeni bir dosya acmak gerek.

**Comment by miratcan** [comment]
:+1:

**Comment by miratcan** [comment]
valla ince görmüşün müdür, hakikaten büyük hata bu.

**Comment by barantr90** [comment]
Ulan ben bunu çoook önce fark etmiştim de bilerek uğraşmıyorsun sanıp konusunu bile açmamıştım 😊
