### ISSUE TITLE
This function why isn't working ?

### ISSUE THREAD

**Issue by nyavuzcan** [Resmin/Resmin#222]
#include<stdio.h>
#include<stdlib.h>
void fonksiyon (int, int);

void fonksiyon(int a, int b){
	int i,j;
	int dizi[a][b];
	for(i=0;i<a;i++){
		
		for(j=0;j<b;j++){
printf("	%d",dizi[i][j]);
}
printf("\n");
}
}

int main () {
		int i,j;
	int a,b;
	int sonuc;
printf("Dizi icin satir sutun gir");

scanf("%d%d",&a,&b);
	int dizi[a][b];
	if(a!=b){
		printf("kare matris icin satir ve sutunlar ayni olmali:");
		exit (0);
	}

		
	
	for(i=0;i<a;i++){
		
		for(j=0;j<b;j++){
	scanf	("%d",&dizi[i][j]);
	
	}
	}
for(i=0;i<a;i++){
		
		for(j=0;j<b;j++){
	printf	("%d	",dizi[i][j]);
	
	}
	printf("\n");
	}

fonksiyon(a,b);

	
	return 0;

}

**Comment by miratcan** [comment]
is it related with this project?

**Comment by fatiherikli** [comment]
yes? @miratcan

**Comment by fatiherikli** [comment]
:trollface:
