### ISSUE TITLE
Twitter, Instagram ve Facebook hesapları bağlama.

### ISSUE THREAD

**Issue by miratcan** [Resmin/Resmin#99]
@gkmngrgn bunu yapabileceğini söyledi, ancak nasıl bir kayıt olma süreci yaşanacak tam anlayamadım. Biri aydınlatabilirse sevinirim.

**Comment by bahattincinic** [comment]
Bunun icin https://github.com/pennersr/django-allauth/ a bakabilirsiniz. Baya guzel, pratik, esnek bla bla :smile:

**Comment by miratcan** [comment]
Kayıt olma fikrinden vazgeçtim. Kayıt olma süreci değişmeyecek kayıt olan kişiler isterlerse bu hesaplarını bağlayıp herhangi bir cevap paylaştıklarında isterlerse sosyal medya hesaplarında paylaşım yapacaklar.

![instagram-sharing-400x460](https://cloud.githubusercontent.com/assets/140968/6314565/05087af0-b9ec-11e4-95c4-ccf7c82aa98e.jpg)
